
kind: Service
apiVersion: v1
metadata:
  name: onlybooks-webserver-service
  labels:
    app: onlybooks-webserver-app
spec:
  selector:
    app: onlybooks-webserver-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP